### ISSUE TITLE
Add Starry's information 

### ISSUE THREAD

**Issue by C-Starry** [HYF-Class20/workflows-group1-intro#11]
Downloaded all software - VS, node, Git
Explored GitHub
Created a folder within VS on the desktop.
Opened the folder using VS and using git clone to clone the workflow repository.
Created a "starry" new branch using git branch.
Switched to the new branch by using "git checkout starry".
Created two new files - "img" and "starry.md".
Entered information in "Starry.md" file and added an image in "img" file.
Checked the changes using "git status".
Committed changes by using git commit -m "add starry info"
Did git push
Verified your code's quality

**Comment by bermarte** [comment]
Verified your code's quality goes before `git push`
All the steps should be like the following:

- [ ] Downloaded all software - VS, node, Git
- [ ] Explored GitHub
...

when you did your tasks, you check them

- [x] Downloaded all software - VS, node, Git
- [x] Explored GitHub
...

Using markdown you write the following to create 2 check-in boxes
```
- [ ] Downloaded all software - VS, node, Git
- [ ] Explored GitHub
...
```

**Comment by GabriellaLohy** [comment]
Closed due to no follow-up until deadline
