### ISSUE TITLE
Renamed Gabriella folder, relocated Jean-Paul folder to groups-bio and renamed it w/o uppercase

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/workflows-group1-intro#18]
There was an issue before that I can't merge my branch due to failed CI check on lint:ls.
After able to find the problem with is Jean Paul folder was written with uppercase. I changed the name without uppercase.

- [ ] Open the master repo on VSCode 
- [ ] `git pull` to get the recent repo version
- [ ] `git checkout lohygabriella`to working on branch called lohygabriella
- [ ] Renamed Bio folder (from me Gabriella) to lohygabriella
- [ ] Relocated Jean Paul's bio to groups-bio folder and renamed his file without using uppercase due to failed npm check for lint:ls
- [ ] `git add .`to submit the changes
- [ ] Run the npm: `npm run format``npm run format:check``npm run spell-check` `npm run lint:ls` `npm run lint:md`
- [ ] All CI check passed
- [ ] `git commit -m "notes why/which file I changed"`
- [ ] `git push origin lohygabriella`

**Comment by bermarte** [comment]
Normally you should have 1 folder only for all the .md files and inside that folder, you should have only .md files and a common folder to place the images. I would use the `bug` label for this issue.
