### ISSUE TITLE
READ ME file, anyone?

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/workflows-group1-intro#21]
We still need to write a nice READ ME file. 
Any volunteer? 🤓

**Comment by saidakf** [comment]
I will try my best to do it 🤓

**Comment by emran-ai** [comment]
and for what exaclty. we haven't recieved any project yet. readme.md files are used to write something about the project and participants on the project.

**Comment by GabriellaLohy** [comment]
[https://github.com/HackYourFutureBelgium/workflows/blob/master/deliverables/group-introduction-repo.md](url) 

Check the assignment carefully. 
We need to make an READ ME file explaining the purpose of our project and also briefly introducing members of the group.
Our coaches explain and mention it so many times on slack..

**Comment by saidakf** [comment]
I finished writing the README file you can check it now

**Comment by saidakf** [comment]
I finished writing the README file you can check it now
