### ISSUE TITLE
To Be Fixed! = Jean Paul = Lint:ls failed check

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/workflows-group1-intro#23]
![Image](https://user-images.githubusercontent.com/124396156/228627310-4fc8767a-ce88-4be0-a337-6edc902f2f1e.png)

Hi Jean Paul!

There's something wrong with your PR. (Check the white block sentences on picture)
Please go back to VSCode and make sure you passed all the npm check.
Folder or path should never have an uppercase, it will causes error.
In your case the npm lint:ls failed due to your folder name; written with uppercase. And also please relocate your bio into groups-bio folder.

Could you please fix it so that I can do my PR?
If it's not fix my branch can't be merged to the master repo.

Thanks in advance!

## Step 1
Make an issue for your PR

## Step 2
- [x] Go to VSCode
- [x] Open your repo
- [x] `git pull` to get the newest version
- [x] `git branch` to check your branch(es)
- [x] `git checkout <branch name you want to work in>` example `git checkout gabriellalohy` 
- [x] Go to your md file and copy it
- [x] `touch ./<folder name you want to put your file>/<your file name with the filename extension>` example `touch./groups-bio/jeanpaul.md` to create a folder/file inside groups-bio
- [x] You will see now your md file located inside the groups-bio folder
- [x] Paste your md file
- [x] `git add ./groups-bio/jeanpaul.md` this command is to add your spesific changes
- [x] `git rm JeanPaul/JeanPaul.md` this command is to delete your past JeanPaul folder with the file inside it; the one that caused CI check
- [x] `git status` to see the changes you've made
- [x] No red message on git status, all green.
- [x] `git commit -m "Fixing lint:ls failed check on JeanPaul folder and file"`
- [x] `npm run format`
- [x] `npm run format:check`
- [x] `npm run spell-check`
- [x] `npm run lint:ls`
- [x] `npm run lint:md`
- [x] All check passed
- [x] Push the code

**Comment by jeanpauliradukunda** [comment]
**Thanks! I fixed the bug, I hope it's working correctly now.**

**Comment by saidakf** [comment]
Close issue
